AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'spec/fixtures/application/htdocs/stylesheets/**/config.rb'
    - 'config/**/*'
    - 'Vagrantfile'
    - 'vendor/**/*'
  TargetRubyVersion: 2.2
  ExtraDetails: true
  DisplayStyleGuide: true
  DisplayCopNames: true
GlobalVars:
  AllowedVariables: []
MethodLength:
  Max: 30
LineLength:
  Max: 200
SpecialGlobalVars:
  Enabled: false
BracesAroundHashParameters:
  Enabled: false
CyclomaticComplexity:
  Max: 10
AbcSize:
  Max: 25
SpaceAfterComma:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
