sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

before_install:
  - gem install bundler --no-doc
  - gem install bundler-audit --no-doc

script:
  - bundle-audit check --update
  - bundle exec rubocop --display-cop-names --extra-details
